### ISSUE TITLE
slideview多个按钮会报错

### ISSUE THREAD

**Issue by glink25** [wechat-miniprogram/weui-miniprogram#105]
slideview列表的第一行按钮如果使用多个按钮会报错，其他行的按钮正常显示
![image](https://user-images.githubusercontent.com/49364151/82297284-034a8f80-99e5-11ea-8d4b-fc3a005af193.png)
报错信息：
`webviewScriptError
Cannot read property 'nv_width' of undefined;[Exparser] [Error] [Component] Event Listener Error @ wx-view#(anonymous)
TypeError: Cannot read property 'nv_width' of undefined
    at nv_touchmove (http://127.0.0.1:42123/__pageframe__/__extendedlib__/weui/pageframe.js:59:2365)
    at i.u.<computed>.<computed>.u.addListener.capture (http://127.0.0.1:42123/__pageframe__/__dev__/WAWebview.js:2:1534851)
    at n.safeCallback (http://127.0.0.1:42123/__pageframe__/__dev__/WAWebview.js:2:193653)
    at n.call (http://127.0.0.1:42123/__pageframe__/__dev__/WAWebview.js:2:193546)
    at o (http://127.0.0.1:42123/__pageframe__/__dev__/WAWebview.js:2:196950)
    at http://127.0.0.1:42123/__pageframe__/__dev__/WAWebview.js:2:197691
    at f (http://127.0.0.1:42123/__pageframe__/__dev__/WAWebview.js:2:196415)
    at Function.l.dispatchEvent (http://127.0.0.1:42123/__pageframe__/__dev__/WAWebview.js:2:197539)
    at _ (http://127.0.0.1:42123/__pageframe__/__dev__/WAWebview.js:2:560997)
    at v (http://127.0.0.1:42123/__pageframe__/__dev__/WAWebview.js:2:561246)
console.error @ VM154:1
(anonymous) @ VM200:2`

**Comment by Tidyzq** [comment]
麻烦提供一下复现代码片段 https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html

**Comment by Tidyzq** [comment]
由于不活跃关闭
