### ISSUE TITLE
Cannot read property 'setModel' of undefined; [Component] Property Observer Error @ miniprogram_npm/weui-miniprogram/form/form#_modelChange

### ISSUE THREAD

**Issue by gushiaoke** [wechat-miniprogram/weui-miniprogram#118]
环境:npm "weui-miniprogram": "^1.0.3"
看最新代码线已经修复了这个问题,请更新npm上的版本

VM31835:1 thirdScriptError
Cannot read property 'setModel' of undefined; [Component] Property Observer Error @ miniprogram_npm/weui-miniprogram/form/form#_modelChange
TypeError: Cannot read property 'setModel' of undefined
    at ge._modelChange (http://127.0.0.1:38588/appservice/miniprogram_npm/weui-miniprogram/form/form.js:424:28)
    at Function.r.safeCallback (WAService.js:1:1133279)
    at n.<anonymous> (WAService.js:1:1225259)
    at a.doUpdates (WAService.js:1:1241052)
    at s (WAService.js:1:1363643)
    at m (WAService.js:1:1281690)
    at p (WAService.js:1:1282375)
    at m (WAService.js:1:1281760)
    at e.value (WAService.js:1:1287515)
    at e.value (WAService.js:1:1286979)

**Comment by gushiaoke** [comment]
![image](https://user-images.githubusercontent.com/7317348/86310706-425d3900-bc51-11ea-8c93-de6ef6eed127.png)

**Comment by Tidyzq** [comment]
fixed in v1.0.4
