### ISSUE TITLE
npm run init 报错 primordials is not defined

### ISSUE THREAD

**Issue by workhardtech** [wechat-miniprogram/weui-miniprogram#14]
const { Math, Object } = primordials;
                         ^
ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Volumes/apple/source/github/weui-miniprogram/src/weui-wxss/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Volumes/apple/source/github/weui-miniprogram/src/weui-wxss/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Volumes/apple/source/github/weui-miniprogram/src/weui-wxss/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by cunjinli6** [comment]
你的gulp版本是多少？我在网上找到了这个https://github.com/gulpjs/gulp/issues/2324，看下能否升级到gulp4试下

**Comment by cunjinli6** [comment]
目前node12下跑会报错，可以升级到gulp4试下。
