### ISSUE TITLE
运行表单，报错

### ISSUE THREAD

**Issue by xzsqhl** [wechat-miniprogram/weui-miniprogram#142]
VM13:1 jsEnginScriptError
Component is not found in path "components/cells/cells" (using by "example/cell/cell");onAppRoute
Error: Component is not found in path "components/cells/cells" (using by "example/cell/cell")
    at q (http://127.0.0.1:63173/appservice/__dev__/WAService.js:2:1560119)
    at q (http://127.0.0.1:63173/appservice/__dev__/WAService.js:2:1560323)
    at http://127.0.0.1:63173/appservice/__dev__/WAService.js:2:1582193
    at Module.He (http://127.0.0.1:63173/appservice/__dev__/WAService.js:2:1582772)
    at Function.value (http://127.0.0.1:63173/appservice/__dev__/WAService.js:2:1673187)
    at Et (http://127.0.0.1:63173/appservice/__dev__/WAService.js:2:1689323)
    at Dt (http://127.0.0.1:63173/appservice/__dev__/WAService.js:2:1691760)
    at Function.<anonymous> (http://127.0.0.1:63173/appservice/__dev__/WAService.js:2:1697665)
    at i.<anonymous> (http://127.0.0.1:63173/appservice/__dev__/WAService.js:2:1666024)
    at i.emit (http://127.0.0.1:63173/appservice/__dev__/WAService.js:2:598598)

**Comment by Tidyzq** [comment]
related to #143
