### ISSUE TITLE
生成的组件库文件不完整

### ISSUE THREAD

**Issue by xiaodouyaer** [wechat-miniprogram/weui-miniprogram#146]
## Bug描述
项目down下来后，根目录运行，npm run init，然后 npm run dev，生成的miniprogram_dev\components 下的各个组件文件都不全，比如form ，仅仅只有.json 和 .wxml 两个文件，这是正常的吗？

**Comment by Tidyzq** [comment]
不正常，请提供以下信息：
- 当前 commit id

**Comment by xiaodouyaer** [comment]
是要这个代码最后提交的id吧：9ab4da5


https://github.com/wechat-miniprogram/weui-miniprogram，在github上down的最新代码


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wechat-miniprogram/weui-miniprogram"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月6日(星期五) 下午5:15
收件人:&nbsp;"wechat-miniprogram/weui-miniprogram"<weui-miniprogram@noreply.github.com&gt;;
抄送:&nbsp;"小豆芽儿"<1090969255@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wechat-miniprogram/weui-miniprogram] 生成的组件库文件不完整 (#146)





 
不正常，请提供以下信息：
  
当前 commit id

**Comment by xiaodouyaer** [comment]
当前 commit id  9ad4da50
nodejs 版本  v12.18.3
npm 版本  6.14.6
操作系统版本 win10 64位专业版
执行 npm run dev 的日志报错信息   
[error.log](https://github.com/wechat-miniprogram/weui-miniprogram/files/5500436/error.log)

**Comment by Tidyzq** [comment]
尝试在weui根目录命令行执行：
```bash
git config core.autocrlf false
git rm --cached -r . 
git reset --hard
```

**Comment by xiaodouyaer** [comment]
非常感谢，按照你的方法，已经成功了

**Comment by mithenji** [comment]
`'weui-miniprogram-copy-weui-wxss' errored after 189 ms
[11:57:38] Error: File not found with singular glob: /Users/mithenji/Documents/Github_Code/weui-miniprogram/src/weui-wxss/dist/style/weui.wxss (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/Users/mithenji/Documents/Github_Code/weui-miniprogram/node_modules/gulp/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (node:events:472:26)
    at Glob.emit (node:events:365:28)
    at Glob.emit (node:domain:470:12)
    at Glob._finish (/Users/mithenji/Documents/Github_Code/weui-miniprogram/node_modules/glob/glob.js:195:8)
    at done (/Users/mithenji/Documents/Github_Code/weui-miniprogram/node_modules/glob/glob.js:180:14)
    at Glob._processSimple2 (/Users/mithenji/Documents/Github_Code/weui-miniprogram/node_modules/glob/glob.js:686:12)
    at /Users/mithenji/Documents/Github_Code/weui-miniprogram/node_modules/glob/glob.js:674:10
    at Glob._stat2 (/Users/mithenji/Documents/Github_Code/weui-miniprogram/node_modules/glob/glob.js:770:12)
    at lstatcb_ (/Users/mithenji/Documents/Github_Code/weui-miniprogram/node_modules/glob/glob.js:762:12)
[11:57:38] 'weui-miniprogram-build' errored after 242 ms
[11:57:38] 'weui-miniprogram-dev' errored after 243 ms
[11:57:38] 'dev' errored after 245 ms
`
帮忙看看这个问题怎么修改
