### ISSUE TITLE
真机调试 searchbar 出错

### ISSUE THREAD

**Issue by dong0** [wechat-miniprogram/weui-miniprogram#18]
1. 按照readme执行npm run init、npm run dev
2. 用开发者工具打开miniprogram_dev目录
3. 使用真机调试，点击“searchbar”后
报JS错误：
jsEnginScriptError
Component is not found in path "components/searchbar/searchbar" (using by "example/searchbar/searchbar");onAppRoute
Error: Component is not found in path "components/searchbar/searchbar" (using by "example/searchbar/searchbar")
    at H (WAService.js:1:1302208)
    at H (WAService.js:1:1302412)
    at WAService.js:1:1319968
    at Module.Fe (WAService.js:1:1320547)
    at Function.value (WAService.js:1:1350860)
    at Tt (WAService.js:1:1366302)
    at WAService.js:1:1368724
    at xt (WAService.js:1:1368770)
    at Function.<anonymous> (WAService.js:1:1374284)
    at i.<anonymous> (WAService.js:1:1343799)

**Comment by huangshunping** [comment]
代码没写usingComponent

**Comment by cunjinli6** [comment]
0.1.8版本更新
