### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by dkvirus** [wechat-miniprogram/weui-miniprogram#2]
按照 README.md 执行完 `npm install` 之后，运行 `npm run dev` 报错。

```
[09:05:49] 'weui-miniprogram-component-wxml' errored after 248 ms
[09:05:49] Error: File not found with singular glob: /Users/dkvirus/Documents/github/weui-miniprogram/src/weui-wxss/dist/style/weui.wxss (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/Users/dkvirus/Documents/github/weui-miniprogram/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:273:13)
    at Glob.emit (events.js:182:13)
    at Glob.EventEmitter.emit (domain.js:441:20)
    at Glob._finish (/Users/dkvirus/Documents/github/weui-miniprogram/node_modules/glob/glob.js:197:8)
    at done (/Users/dkvirus/Documents/github/weui-miniprogram/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/Users/dkvirus/Documents/github/weui-miniprogram/node_modules/glob/glob.js:688:12)
    at /Users/dkvirus/Documents/github/weui-miniprogram/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/Users/dkvirus/Documents/github/weui-miniprogram/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/Users/dkvirus/Documents/github/weui-miniprogram/node_modules/glob/glob.js:764:12)
[09:05:49] 'weui-miniprogram-build' errored after 343 ms
[09:05:49] 'weui-miniprogram-dev' errored after 343 ms
[09:05:49] 'dev' errored after 346 ms
[09:05:49] The following tasks did not complete: weui-miniprogram-component-less, weui-miniprogram-component-json
[09:05:49] Did you forget to signal async completion?
```

看问题找到了 `src/weui-wxss` 目录，貌似该目录下没有 dist 目录导致的。

期望：官方生成 dist 目录，使得 `npm run dev` 能正常启动项目，用户体验友好。

**Comment by cunjinli6** [comment]
麻烦重新初始化(npm run init)项目试下
