### ISSUE TITLE
npm run dev 出错

### ISSUE THREAD

**Issue by anti996sz** [wechat-miniprogram/weui-miniprogram#23]
PS D:\WechatApps\weui-miniprogram-master> npm run dev

> weui-miniprogram@0.1.8 dev D:\WechatApps\weui-miniprogram-master
> gulp dev --develop

[19:12:29] Using gulpfile D:\WechatApps\weui-miniprogram-master\gulpfile.js
[19:12:29] Starting 'dev'...
[19:12:29] Starting 'weui-miniprogram-dev'...
[19:12:29] Starting 'weui-miniprogram-build'...
[19:12:29] Starting 'weui-miniprogram-clean-dist'...
[19:12:29] Finished 'weui-miniprogram-clean-dist' after 31 ms
[19:12:29] Starting 'weui-miniprogram-component-check'...
[19:12:29] Finished 'weui-miniprogram-component-check' after 102 ms
[19:12:29] Starting 'weui-miniprogram-component-wxml'...
[19:12:29] Starting 'weui-miniprogram-component-js'...
[19:12:29] Starting 'weui-miniprogram-component-less'...
[19:12:29] Starting 'weui-miniprogram-component-wxss'...
[19:12:29] Starting 'weui-miniprogram-component-json'...
[19:12:29] Starting 'weui-miniprogram-copy'...
[19:12:29] Starting 'weui-miniprogram-package-json'...
[19:12:29] Finished 'weui-miniprogram-component-js' after 433 ms
[19:12:29] Finished 'weui-miniprogram-component-wxss' after 451 ms
[19:12:29] Starting '<anonymous>'...
[19:12:29] Starting '<anonymous>'...
[19:12:29] Finished 'weui-miniprogram-package-json' after 489 ms
[19:12:29] Finished '<anonymous>' after 11 ms
[19:12:29] Finished '<anonymous>' after 11 ms
[19:12:29] Finished 'weui-miniprogram-copy' after 502 ms
[19:12:29] 'weui-miniprogram-component-wxml' errored after 552 ms
[19:12:29] Error: File not found with singular glob: D:/WechatApps/weui-miniprogram-master/src/weui-wxss/dist/style/weui.wxss (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (D:\WechatApps\weui-miniprogram-master\node_modules\glob-stream\readable.js:84:17)
    at Object.onceWrapper (events.js:297:20)
    at Glob.emit (events.js:209:13)
    at Glob.EventEmitter.emit (domain.js:476:20)
    at Glob._finish (D:\WechatApps\weui-miniprogram-master\node_modules\glob\glob.js:197:8)
    at done (D:\WechatApps\weui-miniprogram-master\node_modules\glob\glob.js:182:14)
    at Glob._processSimple2 (D:\WechatApps\weui-miniprogram-master\node_modules\glob\glob.js:688:12)
    at D:\WechatApps\weui-miniprogram-master\node_modules\glob\glob.js:676:10
    at Glob._stat2 (D:\WechatApps\weui-miniprogram-master\node_modules\glob\glob.js:772:12)
    at lstatcb_ (D:\WechatApps\weui-miniprogram-master\node_modules\glob\glob.js:764:12)
[19:12:29] 'weui-miniprogram-build' errored after 693 ms
[19:12:29] 'weui-miniprogram-dev' errored after 696 ms
[19:12:29] 'dev' errored after 701 ms
[19:12:29] The following tasks did not complete: weui-miniprogram-component-less, weui-miniprogram-component-json
[19:12:29] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! weui-miniprogram@0.1.8 dev: `gulp dev --develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the weui-miniprogram@0.1.8 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\scott.wan\AppData\Roaming\npm-cache\_logs\2019-08-31T11_12_29_852Z-debug.log

**Comment by anti996sz** [comment]
[2019-08-31T11_12_29_852Z-debug.log](https://github.com/wechat-miniprogram/weui-miniprogram/files/3562378/2019-08-31T11_12_29_852Z-debug.log)

**Comment by cunjinli6** [comment]
因为里面引用了submodule，所以要通过git clone下载代码下来，跑npm run init再跑npm run dev

**Comment by acelan86** [comment]
npm run init 解决，建议补充到README.md

**Comment by wechat-miniprogram-admin** [comment]
duplicated #56
