### ISSUE TITLE
gallery中使用了 delete 属性，会导致编译webpack编译失败

### ISSUE THREAD

**Issue by saoraozhe3hao** [wechat-miniprogram/weui-miniprogram#25]
`  <view class="weui-gallery__opr" wx:if="{{delete}}">
    <navigator href="javascript:" bindtap="deleteImg" class="weui-gallery__del">删除</navigator>
  </view>`
`
ERROR in ./node_modules/weui-miniprogram/miniprogram_dist/gallery/gallery.wxml?__resource=D:/personal/mpx/node_modules/weui-miniprogram/miniprogram_dist/gallery/gallery (./node_modules/@mpxjs/webpack-plugin/lib/extractor.js?type=templa
te&index=0!./node_modules/@mpxjs/webpack-plugin/lib/wxml/wxml-loader.js?root=!./node_modules/@mpxjs/webpack-plugin/lib/template-compiler?{"usingComponents":["van-tabbar","van-tabbar-item"],"hasScoped":false,"hasComment":false,"isNative
":true,"moduleId":"5f0bf755"}!./node_modules/weui-miniprogram/miniprogram_dist/gallery/gallery.wxml?__resource=D:/personal/mpx/node_modules/weui-miniprogram/miniprogram_dist/gallery/gallery)
Module build failed (from ./node_modules/@mpxjs/webpack-plugin/lib/template-compiler/index.js):
SyntaxError: Unexpected token )
    at new Function (<anonymous>)
    at evalExp (D:\personal\mpx\node_modules\@mpxjs\webpack-plugin\lib\template-compiler\compiler.js:1264:14)
    at postProcessIf (D:\personal\mpx\node_modules\@mpxjs\webpack-plugin\lib\template-compiler\compiler.js:1279:14)
    at closeElement (D:\personal\mpx\node_modules\@mpxjs\webpack-plugin\lib\template-compiler\compiler.js:1570:3)
    at Object.end (D:\personal\mpx\node_modules\@mpxjs\webpack-plugin\lib\template-compiler\compiler.js:740:9)
    at parseEndTag (D:\personal\mpx\node_modules\@mpxjs\webpack-plugin\lib\template-compiler\compiler.js:463:19)
    at parseHTML (D:\personal\mpx\node_modules\@mpxjs\webpack-plugin\lib\template-compiler\compiler.js:273:11)
    at Object.parse (D:\personal\mpx\node_modules\@mpxjs\webpack-plugin\lib\template-compiler\compiler.js:665:3)
    at Object.module.exports (D:\personal\mpx\node_modules\@mpxjs\webpack-plugin\lib\template-compiler\index.js:23:25)
 @ ./node_modules/weui-miniprogram/miniprogram_dist/gallery/gallery.js (./node_modules/@mpxjs/webpack-plugin/lib/native-loader.js?{"transRpx":{"mode":"only","comment":"use rpx","include":"D://personal//mpx//src"}}!./node_modules/weui-m
iniprogram/miniprogram_dist/gallery/gallery.js) 9:0-451

`

**Comment by cunjinli6** [comment]
这个webpack构建是你们自己的构建脚本？还不大清楚你们的构建逻辑

**Comment by saoraozhe3hao** [comment]
delete 是 js 的关键字，不应该拿来当标识符。@mpxjs\webpack-plugin\lib\template-compiler\compiler.js 报的错

**Comment by cunjinli6** [comment]
嗯，接下来的v0.2版本再改下这个字段

**Comment by cunjinli6** [comment]
v0.2版本改成了showDelete属性
