### ISSUE TITLE
npm run init 解决，建议补充到README.md

### ISSUE THREAD

**Issue by pandora1451** [wechat-miniprogram/weui-miniprogram#56]
npm run init 解决，建议补充到README.md

_Originally posted by @acelan86 in https://github.com/wechat-miniprogram/weui-miniprogram/issues/23#issuecomment-540518033_

我也是这么觉得，补充一下吧。

**Comment by hemosoul** [comment]
太傲慢了？

**Comment by chengkaii** [comment]
试了还是失败

- `kk@KKdeMacBook-Pro trunk % cnpm run init

> weui-miniprogram@0.1.12 init /Users/kk/WeChatProjects/weui-miniprogram.git/trunk
> npm run submodule && npm i && cd src/weui-wxss && npm i && gulp build:style && cd ../../ && npm run dev


> weui-miniprogram@0.1.12 submodule /Users/kk/WeChatProjects/weui-miniprogram.git/trunk
> git submodule init && git submodule update --init --remote

fatal: not a git repository (or any of the parent directories): .git
npm ERR! code ELIFECYCLE
npm ERR! errno 128
npm ERR! weui-miniprogram@0.1.12 submodule: `git submodule init && git submodule update --init --remote`
npm ERR! Exit status 128
npm ERR! 
npm ERR! Failed at the weui-miniprogram@0.1.12 submodule script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kk/.npm/_logs/2019-11-25T17_34_46_250Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 128
npm ERR! weui-miniprogram@0.1.12 init: `npm run submodule && npm i && cd src/weui-wxss && npm i && gulp build:style && cd ../../ && npm run dev`
npm ERR! Exit status 128
npm ERR! 
npm ERR! Failed at the weui-miniprogram@0.1.12 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kk/.npm/_logs/2019-11-25T17_34_46_277Z-debug.log
kk@KKdeMacBook-Pro trunk % cnpm install
✔ Installed 30 packages
✔ Linked 851 latest versions
[1/2] scripts.postinstall babel-preset-env@1.7.0 › babel-plugin-check-es2015-constants@6.22.0 › babel-runtime@6.26.0 › core-js@^2.4.0 run "node postinstall || echo \"ignore\"", root: "/Users/kk/WeChatProjects/weui-miniprogram.git/trunk/node_modules/_core-js@2.6.10@core-js"
Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

[1/2] scripts.postinstall babel-preset-env@1.7.0 › babel-plugin-check-es2015-constants@6.22.0 › babel-runtime@6.26.0 › core-js@^2.4.0 finished in 90ms
[2/2] scripts.install gulp@4.0.2 › glob-watcher@5.0.3 › chokidar@2.1.8 › fsevents@^1.2.7 run "node install", root: "/Users/kk/WeChatProjects/weui-miniprogram.git/trunk/node_modules/_fsevents@1.2.9@fsevents"
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp http GET https://cdn.npm.taobao.org/dist/fsevents/v1.2.9/fse-v1.2.9-node-v72-darwin-x64.tar.gz
node-pre-gyp http 200 https://cdn.npm.taobao.org/dist/fsevents/v1.2.9/fse-v1.2.9-node-v72-darwin-x64.tar.gz
[fsevents] Success: "/Users/kk/WeChatProjects/weui-miniprogram.git/trunk/node_modules/_fsevents@1.2.9@fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote
[2/2] scripts.install gulp@4.0.2 › glob-watcher@5.0.3 › chokidar@2.1.8 › fsevents@^1.2.7 finished in 2s
✔ Run 2 scripts
deprecate autoprefixer@6.7.7 › browserslist@^1.7.6 Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
deprecate babel-preset-env@1.7.0 › babel-plugin-check-es2015-constants@6.22.0 › babel-runtime@6.26.0 › core-js@^2.4.0 core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
deprecate gulp-install@1.1.0 › gulp-util@^3.0.7 gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
deprecate gulp@4.0.2 › glob-watcher@5.0.3 › chokidar@2.1.8 › fsevents@^1.2.7 One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
deprecate jest@23.6.0 › jest-cli@23.6.0 › prompts@0.1.14 › kleur@^2.0.1 Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
Recently updated (since 2019-11-19): 13 packages (detail see file /Users/kk/WeChatProjects/weui-miniprogram.git/trunk/node_modules/.recently_updates.txt)
  Today:
    → jest@23.6.0 › jest-cli@23.6.0 › istanbul-api@1.3.7 › istanbul-reports@1.5.1 › handlebars@4.5.3 › uglify-js@^3.1.4(3.7.0) (01:01:04)
✔ All packages installed (1004 packages installed from npm registry, used 46s(network 44s), speed 50.9kB/s, json 881(2.21MB), tarball 0B)
kk@KKdeMacBook-Pro trunk % cnpm run dev

> weui-miniprogram@0.1.12 dev /Users/kk/WeChatProjects/weui-miniprogram.git/trunk
> gulp dev --develop

[01:36:53] Using gulpfile ~/WeChatProjects/weui-miniprogram.git/trunk/gulpfile.js
[01:36:53] Starting 'dev'...
[01:36:53] Starting 'weui-miniprogram-dev'...
[01:36:53] Starting 'weui-miniprogram-build'...
[01:36:53] Starting 'weui-miniprogram-clean-dist'...
[01:36:54] Finished 'weui-miniprogram-clean-dist' after 9.64 ms
[01:36:54] Starting 'weui-miniprogram-component-check'...
[01:36:54] Finished 'weui-miniprogram-component-check' after 134 ms
[01:36:54] Starting 'weui-miniprogram-component-wxml'...
[01:36:54] Starting 'weui-miniprogram-component-js'...
[01:36:54] Starting 'weui-miniprogram-component-less'...
[01:36:54] Starting 'weui-miniprogram-component-wxss'...
[01:36:54] Starting 'weui-miniprogram-component-json'...
[01:36:54] Starting 'weui-miniprogram-copy'...
[01:36:54] Starting 'weui-miniprogram-package-json'...
[01:36:54] Finished 'weui-miniprogram-component-js' after 179 ms
[01:36:54] Finished 'weui-miniprogram-component-wxss' after 185 ms
[01:36:54] Starting '<anonymous>'...
[01:36:54] Starting '<anonymous>'...
[01:36:54] Finished 'weui-miniprogram-package-json' after 202 ms
[01:36:54] Finished '<anonymous>' after 2.71 ms
[01:36:54] Finished '<anonymous>' after 2.85 ms
[01:36:54] Finished 'weui-miniprogram-copy' after 204 ms
[01:36:54] 'weui-miniprogram-component-wxml' errored after 228 ms
[01:36:54] Error: File not found with singular glob: /Users/kk/WeChatProjects/weui-miniprogram.git/trunk/src/weui-wxss/dist/style/weui.wxss (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/Users/kk/WeChatProjects/weui-miniprogram.git/trunk/node_modules/_glob-stream@6.1.0@glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:300:26)
    at Glob.emit (events.js:210:5)
    at Glob.EventEmitter.emit (domain.js:475:20)
    at Glob._finish (/Users/kk/WeChatProjects/weui-miniprogram.git/trunk/node_modules/_glob@7.1.6@glob/glob.js:197:8)
    at done (/Users/kk/WeChatProjects/weui-miniprogram.git/trunk/node_modules/_glob@7.1.6@glob/glob.js:182:14)
    at Glob._processSimple2 (/Users/kk/WeChatProjects/weui-miniprogram.git/trunk/node_modules/_glob@7.1.6@glob/glob.js:688:12)
    at /Users/kk/WeChatProjects/weui-miniprogram.git/trunk/node_modules/_glob@7.1.6@glob/glob.js:676:10
    at Glob._stat2 (/Users/kk/WeChatProjects/weui-miniprogram.git/trunk/node_modules/_glob@7.1.6@glob/glob.js:772:12)
    at lstatcb_ (/Users/kk/WeChatProjects/weui-miniprogram.git/trunk/node_modules/_glob@7.1.6@glob/glob.js:764:12)
[01:36:54] 'weui-miniprogram-build' errored after 376 ms
[01:36:54] 'weui-miniprogram-dev' errored after 377 ms
[01:36:54] 'dev' errored after 379 ms
[01:36:54] The following tasks did not complete: weui-miniprogram-component-less, weui-miniprogram-component-json
[01:36:54] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! weui-miniprogram@0.1.12 dev: `gulp dev --develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the weui-miniprogram@0.1.12 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kk/.npm/_logs/2019-11-25T17_36_54_385Z-debug.log
kk@KKdeMacBook-Pro trunk % `

**Comment by hhayyok** [comment]
直接给打包发布一个不行吗

**Comment by wechat-miniprogram-admin** [comment]
已补充
