### ISSUE TITLE
新人提问：代码下载了无法init？

### ISSUE THREAD

**Issue by tanjun2030** [wechat-miniprogram/weui-miniprogram#90]
难道只有我一个人下载了代码不能进行init吗？
`npm run init

> weui-miniprogram@0.2.2 init /Users/tanjun/WeChatProjects/weui-miniprogram-master
> npm run submodule && npm i && cd src/weui-wxss && npm i && gulp build:style && cd ../../ && npm run dev

> weui-miniprogram@0.2.2 submodule /Users/tanjun/WeChatProjects/weui-miniprogram-master
> git submodule init && git submodule update --init

audited 264140 packages in 8.679s

29 packages are looking for funding
  run `npm fund` for details

found 7 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
audited 264140 packages in 6.933s

29 packages are looking for funding
  run `npm fund` for details

found 7 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
[16:22:54] Working directory changed to ~/WeChatProjects/weui-miniprogram-master
[16:22:54] Using gulpfile ~/WeChatProjects/weui-miniprogram-master/gulpfile.js
[16:22:54] Task never defined: build:style
[16:22:54] To list available tasks, try running: gulp --tasks
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! weui-miniprogram@0.2.2 init: `npm run submodule && npm i && cd src/weui-wxss && npm i && gulp build:style && cd ../../ && npm run dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the weui-miniprogram@0.2.2 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

`

按这个提示一通操作猛如虎，发现还是不行；

然后直接执行 npm run dev,依然报错：
`'weui-miniprogram-component-wxml' errored after 189 ms
[16:35:37] Error: File not found with singular glob: /Users/tanjun/WeChatProjects/weui-miniprogram-master/src/weui-wxss/dist/style/weui.wxss (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/Users/tanjun/WeChatProjects/weui-miniprogram-master/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:418:26)
    at Glob.emit (events.js:311:20)
    at Glob.EventEmitter.emit (domain.js:482:12)
    at Glob._finish (/Users/tanjun/WeChatProjects/weui-miniprogram-master/node_modules/glob/glob.js:197:8)
    at done (/Users/tanjun/WeChatProjects/weui-miniprogram-master/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/Users/tanjun/WeChatProjects/weui-miniprogram-master/node_modules/glob/glob.js:688:12)
    at /Users/tanjun/WeChatProjects/weui-miniprogram-master/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/Users/tanjun/WeChatProjects/weui-miniprogram-master/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/Users/tanjun/WeChatProjects/weui-miniprogram-master/node_modules/glob/glob.js:764:12)
[16:35:37] 'weui-miniprogram-build' errored after 240 ms
[16:35:37] 'weui-miniprogram-dev' errored after 240 ms
[16:35:37] 'dev' errored after 242 ms
[16:35:37] The following tasks did not complete: weui-miniprogram-component-less, weui-miniprogram-component-json
[16:35:37] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! weui-miniprogram@0.2.2 dev: `gulp dev --develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the weui-miniprogram@0.2.2 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by rayyzhong** [comment]
Why this issue was closed without reason...

I am facing same problem.
